openapi: "3.0.3"
info:
  title: Task Management API
  version: "1.2.0"
  description: >
    A REST API for managing tasks. In-memory storage using sync.RWMutex + map.
    Standard library net/http with Go 1.22+ routing patterns. CORS enabled.

servers:
  - url: http://localhost:8080

paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: Service is healthy
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    example: ok

  /tasks:
    get:
      summary: List all tasks
      description: Returns tasks sorted by created_at ascending (deterministic order).
      parameters:
        - name: status
          in: query
          required: false
          schema:
            type: string
            enum: [todo, in_progress, done]
      responses:
        "200":
          description: Array of tasks sorted by created_at ascending
          content:
            application/json:
              schema:
                type: object
                properties:
                  tasks:
                    type: array
                    items:
                      $ref: "#/components/schemas/Task"
        "400":
          description: Invalid status filter value
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    post:
      summary: Create a new task
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/CreateTaskRequest"
      responses:
        "201":
          description: Task created
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "500":
          description: Internal error (UUID generation failure)
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

  /tasks/{id}:
    get:
      summary: Get a task by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "200":
          description: The task
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "404":
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    put:
      summary: Update a task (partial)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/UpdateTaskRequest"
      responses:
        "200":
          description: Task updated
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Task"
        "400":
          description: Invalid request body
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"
        "404":
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

    delete:
      summary: Delete a task
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        "204":
          description: Task deleted
        "404":
          description: Task not found
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorResponse"

components:
  schemas:
    Task:
      type: object
      properties:
        id:
          type: string
          format: uuid
        title:
          type: string
        description:
          type: string
        status:
          type: string
          enum: [todo, in_progress, done]
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      required: [id, title, status, created_at, updated_at]

    CreateTaskRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          maxLength: 4096
      required: [title]

    UpdateTaskRequest:
      type: object
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 255
        description:
          type: string
          maxLength: 4096
        status:
          type: string
          enum: [todo, in_progress, done]

    ErrorResponse:
      type: object
      properties:
        error:
          type: string
      required: [error]

x-implementation-notes:
  routing: >
    Use Go 1.22+ ServeMux patterns: "GET /health", "GET /tasks", "POST /tasks",
    "GET /tasks/{id}", "PUT /tasks/{id}", "DELETE /tasks/{id}".
    The {id} wildcard is accessed via r.PathValue("id").
  cors: >
    CORS middleware: Origin *, methods GET/POST/PUT/DELETE/OPTIONS,
    headers Content-Type. OPTIONS returns 204 immediately.
    Wrap the mux: srv.Handler = corsMiddleware(mux).
  body-limit: >
    Wrap r.Body with http.MaxBytesReader(w, r.Body, 1<<20) in POST/PUT handlers
    to cap request bodies at 1 MiB.
  error-format: >
    All error responses use {"error": "message"} shape.
    writeJSON must log encode errors via log.Printf — do not silently discard them.
  module: >
    Backend directory must contain go.mod with: module taskapi, go 1.22.
    Standard library only — no external dependencies.
